# Generated by Django 3.2.4 on 2021-06-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('explanation', models.TextField(blank=True)),
                ('reservation_available', models.BooleanField()),
                ('charge_available', models.BooleanField()),
                ('total_seats', models.SmallIntegerField()),
                ('used_seats', models.SmallIntegerField(null=True)),
                ('unused_seats', models.SmallIntegerField(null=True)),
                ('congestion_status', models.SmallIntegerField()),
                ('lat', models.SmallIntegerField()),
                ('lng', models.SmallIntegerField()),
                ('thumbnail', models.ImageField(default='#', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('out_of_stock', models.BooleanField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_image', models.ImageField(upload_to='')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.IntegerField(default=0)),
                ('prizes', models.TextField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cafe')),
            ],
        ),
    ]
