# Generated by Django 3.2.4 on 2021-06-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cafe_phone_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='close_day',
            field=models.TextField(blank=True, choices=[('MON', '월요일'), ('TUS', '화요일'), ('WEN', '수요일'), ('THR', '목요일'), ('FRI', '금요일'), ('SAT', '토요일'), ('SON', '일요일')]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='free_coupon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafe',
            name='congestion_status',
            field=models.SmallIntegerField(choices=[(0, '여유'), (1, '보통'), (2, '혼잡')], default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='prizes',
            field=models.TextField(default='아메리카노 1잔'),
        ),
        migrations.CreateModel(
            name='Queuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('used_table', models.IntegerField(default=0)),
                ('waiting_team', models.IntegerField(default=0)),
                ('estimated_latency_default', models.IntegerField(default=30)),
                ('estimated_latency', models.IntegerField(default=0)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cafe')),
            ],
        ),
    ]
