# Generated by Django 3.2.4 on 2021-06-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuing',
            name='total',
        ),
        migrations.RemoveField(
            model_name='queuing',
            name='used_table',
        ),
        migrations.AddField(
            model_name='cafe',
            name='number_of_reivew',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='rating',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='sum_of_reivew',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='steamed_list',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuing',
            name='wating_number',
            field=models.IntegerField(default=1),
        ),
    ]
