# Generated by Django 3.2.4 on 2021-07-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210628_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.customuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PersonalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queuing_id', models.IntegerField()),
                ('wating_number', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
